### PR TITLE
Fix Erroneous IPA for "you" and "yong"

### LINKED ISSUE #25: Wrong IPA for  yong &  you in transcriptions.csv
Correct IPA  transcriptions:
```
yong  -> iʊŋ
you   -> ioʊ
```

### PR DESCRIPTION
**Pull request by boyleconnor**
Fixes #25. See [this](https://en.wikipedia.org/wiki/Pinyin#Comparison_charts) for correct phonemes for *you* and *yong*

### CODE REVIEW

**Comment by cascadianblue** [comment]
@tsroten is this repository still being maintained?

**Comment by tsroten** [comment]
I've pushed this commit and am releasing it now. Thanks for the contribution, and sorry for the delay 😄

**Comment by boyleconnor** [comment]
@tsroten was there something wrong with my commit?

**Comment by tsroten** [comment]
There was a merge conflict, and given the long delay in me looking at this, I didn't feel good about pinging you to fix it. Thanks again!

**Pull request closed without merging**
